### ISSUE TITLE
Checks

### ISSUE THREAD

**Issue by colebemis** [primer/octicons-v2#136]
![image](https://user-images.githubusercontent.com/4608155/70946877-d7c61200-200c-11ea-9379-f9bba46a0bab.png)

**Comment by colebemis** [comment]
Here's what the issue/PR UI looks like with the checkbox icon:

![image](https://user-images.githubusercontent.com/4608155/74508950-2ed54f80-4eb5-11ea-9298-f67b18cfe231.png)

What do y'all think?

**Comment by jasonlong** [comment]
I think it looks beautiful. Is there any concern about how much it looks like an interactive element though? 🤔

**Comment by ashygee** [comment]
@jasonlong I think having it in the lighter gray color will make it feel less interactive but that's definitely something we should test for. If anything we will still have the checks icon that looks more like a list, and we are also going to test how using the circle-check feels in the PR tab nav.
