### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by colebemis** [primer/octicons-v2#139]
![image](https://user-images.githubusercontent.com/4608155/70947437-fd075000-200d-11ea-9f77-bd85fe7ad112.png)

**Comment by colebemis** [comment]
Ooo I love this direction, @ashygee! 😄 What if we kept the circles (instead of squares)? I think circles would align nicely with the Actions marketing icons and open circles are kind of a brand element for GitHub.

| Before | After |
| :-: | :-: |
| <img width="16" alt="Frame 1208" src="https://user-images.githubusercontent.com/4608155/74562564-f6b72680-4f1f-11ea-98f9-639846fb513f.png"> | <img width="16" alt="workflow" src="https://user-images.githubusercontent.com/4608155/74562573-fc147100-4f1f-11ea-835c-311d4c453f54.png"> |

<img width="356" alt="Screen Shot 2020-02-14 at 11 48 53 AM" src="https://user-images.githubusercontent.com/4608155/74562598-09c9f680-4f20-11ea-8d46-ee7503983fe7.png">

**Comment by ashygee** [comment]
@colebemis we discussed that but went with squares to differentiate from forking and branching

**Comment by colebemis** [comment]
Ah, I see. That makes sense. Okay, I'm good with this new icon. Added to the viewer ✅
