### ISSUE TITLE
All workflows

### ISSUE THREAD

**Issue by colebemis** [primer/octicons-v2#140]
![image](https://user-images.githubusercontent.com/4608155/70947469-0e505c80-200e-11ea-85f3-b0007b085b0f.png)

**Comment by edokoa** [comment]
@colebemis commented: "I think we can remove all usages of this icon, so we don't need to design a v2 icon for it. @ashygee knows more about this"

Would we make the newer version of this icon or find a substitution?

**Comment by colebemis** [comment]
This is not used in dotcom anymore
