### ISSUE TITLE
Icons for GitHub Insights

### ISSUE THREAD

**Issue by cmwinters** [primer/octicons-v2#143]
Hey all! Just wanted to chime in about some icons that would be nice to have for GitHub Insights.

We're still using material icons in a few places on GitHub Insights because we don't have an equivalent Octicon.  

- Line chart/area chart
  - <img width="135" alt="Image 2019-12-18 at 8 49 48 AM" src="https://user-images.githubusercontent.com/1295166/71106019-694f9400-2173-11ea-974c-9be65d65e26d.png">
- We may also need a scatterchart icon in the future
  - <img width="88" alt="Image 2019-12-18 at 8 53 36 AM" src="https://user-images.githubusercontent.com/1295166/71106264-e67b0900-2173-11ea-9986-08c1e498e440.png">

**Comment by ashygee** [comment]
@edokoa I'm going to close this now that we have the icons currently needed as 3 separate issues.

cc @TheDamianHdez
