### ISSUE TITLE
Ellipsis

### ISSUE THREAD

**Issue by ashygee** [primer/octicons-v2#180]

**Comment by edokoa** [comment]
Would we go with this one then?

Do we need a 24px version?

![image](https://user-images.githubusercontent.com/694831/83035566-e7c13380-a039-11ea-9c99-8668678327c8.png)

**Comment by ashygee** [comment]
I think I prefer what you had going on here @edokoa 
![image](https://user-images.githubusercontent.com/10384315/83203876-47cddd80-a0ff-11ea-8d70-da2b77b41579.png)

**Comment by edokoa** [comment]
With and without border here

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=1119%3A3282


The solid one is closer to the current one, maybe the border one is complex for a small size. Would we need a 24px?

![image](https://user-images.githubusercontent.com/694831/83267882-21727580-a1c5-11ea-8578-708d2945e5eb.png)

**Comment by colebemis** [comment]
I like the solid one ❤️ The outline one feels cluttered and blurry and I don't think there is a need for it. I'm okay with only having a solid version of this icon. Should we call it `ellipsis-fill` or just `ellipsis`?

Re: 24px — This icon is meant to be used inline with text so I can't imagine a 24px use for it.

**Comment by colebemis** [comment]
I opened a PR to add this to Octicons: primer/octicons#435

I'll merge when I have approvals from @ashygee and @edokoa
