### ISSUE TITLE
No newline

### ISSUE THREAD

**Issue by ashygee** [primer/octicons-v2#182]
![image](https://user-images.githubusercontent.com/694831/73352091-a89ff300-4290-11ea-87b8-f451fa5d1f24.png)

**Comment by ashygee** [comment]
I'll add a UI screenshot for how this might look if we just use the `x` icon

**Comment by ashygee** [comment]
Here's what it looks like with the `x` icon:

<img width="306" alt="Screenshot 2020-02-15 15 19 18" src="https://user-images.githubusercontent.com/10384315/74596626-a5ce2d80-5006-11ea-9304-12d0c83aed6c.png">
<img width="366" alt="Screenshot 2020-02-15 15 19 32" src="https://user-images.githubusercontent.com/10384315/74596629-a797f100-5006-11ea-9ef7-4a13a7f97a0f.png">

It looks a little bit like there's an error on the line so I'm not sure if I feel 💯 about this solution. I think I like the "do not enter" imagery better.

> ![image](https://user-images.githubusercontent.com/694831/74331220-8380a980-4d93-11ea-8940-cee98a77077b.png)

I do have a concern that the circle is a different size than the other icons with a circle form as the main visual element. So I feel a bit torn since it is not balanced with the monospaced text in the diff. 

cc/ @colebemis @edokoa

**Comment by edokoa** [comment]
I worry the X could look like an error or some kind of marker. Would it make sense at some point to just drop the icon and / or use some kind of EOF element? I'm even thinking if it has to be red or if it would be enough with a subtle color (gray), as it's only signaling an element or noting down the file finishes there. It doesn't really carry a negative meaning.

**Comment by colebemis** [comment]
> Would it make sense at some point to just drop the icon and / or use some kind of EOF element?

Here's what it looks like using just `EOF` instead of an icon:

<img width="657" alt="Screen Shot 2020-02-17 at 7 47 42 PM" src="https://user-images.githubusercontent.com/4608155/74772420-cf749800-5244-11ea-9323-4211fac468ee.png">

<img width="196" alt="Screen Shot 2020-02-18 at 11 52 39 AM" src="https://user-images.githubusercontent.com/4608155/74772615-34c88900-5245-11ea-9172-e71a3dae8b7a.png">


I kind of like the simplicity of this. What do y'all think?

**Comment by ashygee** [comment]
@colebemis please add the no-entry icon for no-newline that @edokoa created https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2?node-id=527%3A1405

**Comment by colebemis** [comment]
@ashygee Should we call the icon `no-entry` or `no-newline`?

**Comment by ashygee** [comment]
@colebemis I feel like if we call it `no-newline` and someone picks it up later to use as another "do not pass go/no entry/everything stops here" situation we'll get a lot of confusing `no-newline` use cases. 😐

**Comment by colebemis** [comment]
I’m stilly pretty uncertain about the “no entry” metaphor for no newline. I’ll add the icon as `no-entry` to the viewer for now but I think getting opinions from product designers would be helpful for this one.

**Comment by ashygee** [comment]
That works, I agree that opening up the conversation to the other product designers is a great idea.
