### ISSUE TITLE
Zap

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#184]
![image](https://user-images.githubusercontent.com/694831/73432739-a8146480-4343-11ea-838c-76f4be7e7c1d.png)

**Comment by edokoa** [comment]
I think it depends on where we want to use this icon. I was going to say that I somehow prefer the left one, but we can pick either or try to make a new one.

**Comment by colebemis** [comment]
@edokoa I prefer the left one as well.

**Comment by ashygee** [comment]
@edokoa ooh my gatorade lightning bolt! I prefer the left too. Is this only the 16px version?

**Comment by edokoa** [comment]
I wanted to work a little bit more on it. I have the feeling it's a little bit tilted.

**Comment by edokoa** [comment]
What about this one?

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=1119%3A3260

![image](https://user-images.githubusercontent.com/694831/83267056-fb000a80-a1c3-11ea-8a79-43fff1e7934a.png)

![image](https://user-images.githubusercontent.com/694831/83267091-04897280-a1c4-11ea-9f51-9dfbe46bd923.png)


I adjusted the tilt and touched the lines to be parallel.

**Comment by colebemis** [comment]
What if we aligned the middle lines like this?

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2---Source?node-id=1148%3A1784

![image](https://user-images.githubusercontent.com/4608155/83464087-ac04e000-a424-11ea-9c69-55ed526c5c2f.png)

![image](https://user-images.githubusercontent.com/4608155/83464113-bd4dec80-a424-11ea-938b-5ffe754988cb.png)

**Comment by ashygee** [comment]
I like this @colebemis

**Comment by edokoa** [comment]
Me too

**Comment by edokoa** [comment]
https://github.com/primer/octicons/pull/438#event-3410008561
