### ISSUE TITLE
Watch (Wristwatch)

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#188]
![image](https://user-images.githubusercontent.com/694831/73433148-794abe00-4344-11ea-9064-d881b0674052.png)

**Comment by colebemis** [comment]
What about something like this (right)?

![image](https://user-images.githubusercontent.com/4608155/74773580-fcc24580-5246-11ea-9426-cfbdd5b21b45.png)

**Comment by colebemis** [comment]
How about this?
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2---Source?node-id=697%3A1430
![image](https://user-images.githubusercontent.com/4608155/74810596-90762f00-52a4-11ea-9baa-6eb02faf9dab.png)

**Comment by edokoa** [comment]
Yeah, it fits better in the set.

![image](https://user-images.githubusercontent.com/694831/74819477-bb8e6c00-5300-11ea-94d4-8a7b529cbf09.png)

**Comment by colebemis** [comment]
Which shape do y'all prefer?

![image](https://user-images.githubusercontent.com/4608155/74852625-b0800f80-52f1-11ea-90ab-d2cad7b7758d.png)

**Comment by edokoa** [comment]
The right one.
