### ISSUE TITLE
Megaphone

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#193]
![image](https://user-images.githubusercontent.com/694831/73435361-c0d34900-4348-11ea-94c7-c4fd5e80111d.png)

**Comment by ashygee** [comment]
> New version
> 
> https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2?node-id=335%3A2627
> ![image](https://user-images.githubusercontent.com/694831/73561874-2b27de80-445a-11ea-8bdd-6746bf9cb156.png)

I like this one best. @colebemis can you add this to the viewer?

**Comment by ashygee** [comment]
@edokoa are you good with this version? I think it may not be necessary to have the sound lines and the longer bell allows the icon to look more like a megaphone and less like an axe 🪓. If you're good with this then we can close this issue.

**Comment by edokoa** [comment]
Yeah, I'm good with it.

**Comment by edokoa** [comment]
Bump fix

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=736%3A1425
