### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#203]
![image](https://user-images.githubusercontent.com/694831/73436552-042eb700-434b-11ea-9d6d-995a01d18076.png)

New icons
#104 (Heading)
![image](https://user-images.githubusercontent.com/694831/73436721-5a035f00-434b-11ea-8c4d-1a820aeadc68.png)

**Comment by ashygee** [comment]
@colebemis I like the 3rd one too. The A is much more proportional now with it's lowercase companion.

@edokoa what do you think?

**Comment by edokoa** [comment]
yeah!

![image](https://user-images.githubusercontent.com/694831/74526775-65967e80-4f24-11ea-9f1e-afdb3496f2d4.png)
