### ISSUE TITLE
Sign out

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#205]
![image](https://user-images.githubusercontent.com/694831/73438718-c2a00b00-434e-11ea-8e96-812c89d9d359.png)

Related to #214 (Sign in)

**Comment by colebemis** [comment]
Found in the UI:

![image](https://user-images.githubusercontent.com/4608155/74774836-4e6bcf80-5249-11ea-9bd7-f26456a51751.png)

**Comment by ashygee** [comment]
Notes from today's sync:

We're moving forward with this styling.
![image](https://user-images.githubusercontent.com/10384315/74778135-cf2dca00-524f-11ea-974c-b0b3cbf259df.png)

Which is captured in #214
