### ISSUE TITLE
Primitive square

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#206]
![image](https://user-images.githubusercontent.com/694831/73438757-d77c9e80-434e-11ea-8cac-2fb94ca02a9f.png)

**Comment by edokoa** [comment]
I reopen this one with this https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=1109%3A1789

I'm assuming the icon is a full area black square, so I directly made a 16px and 24px version. Would we need to leave margin in the 24px version?

![image](https://user-images.githubusercontent.com/694831/83013790-e08c2c80-a01d-11ea-869a-0982557f09ed.png)

**Comment by ashygee** [comment]
Yeah I assume that too but I'm not sure if we need to have a fill and stroke version. @colebemis do you know?

**Comment by colebemis** [comment]
Square is used as a build status icon so I think it should be proportional to the `dot` icon: 
![image](https://user-images.githubusercontent.com/4608155/83669605-ac1cf100-a586-11ea-8671-23565d15b55c.png)

Also, we don't use an outline square anywhere but I think we should have it to be consistent with `dot`.

**Comment by colebemis** [comment]
I opened a PR to add `square` to octicons v2: https://github.com/primer/octicons/pull/439
