### ISSUE TITLE
File binary

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#208]
![image](https://user-images.githubusercontent.com/694831/73438887-0b57c400-434f-11ea-8368-0ec3feef28a3.png)

**Comment by colebemis** [comment]
What if we shortened the bottom line a bit? I think it follows the outline of the base file icon a little better.

| Before | After |
| --- | --- |
| <img width="16" alt="file binary" src="https://user-images.githubusercontent.com/4608155/74808702-50ad4880-52a0-11ea-9fcd-c4c370d6b916.png"> | <img width="16" alt="file binary (1)" src="https://user-images.githubusercontent.com/4608155/74808745-66bb0900-52a0-11ea-8072-961e6000c3a8.png"> |

![image](https://user-images.githubusercontent.com/4608155/74808584-0926bc80-52a0-11ea-8024-066aaaa89fde.png)

**Comment by edokoa** [comment]
Yes, it makes more sense, but doesn't it feel like the icon is "falling" to the left when you make the line shorter? Like it has less support and the number symbol makes it too heavy?

I was also doubting with this detail when working on the icon.

**Comment by colebemis** [comment]
Unrelated to the bottom line, what do you think of a `1` in this style?

![image](https://user-images.githubusercontent.com/4608155/74878166-a115bc00-531b-11ea-8fed-1353150eb730.png)

**Comment by edokoa** [comment]
![image](https://user-images.githubusercontent.com/694831/74939713-a7299c80-53f0-11ea-8555-34da2be0f855.png)

I'm fine with both. It's more clear that it's a character and not a line.

**Comment by edokoa** [comment]
@ashygee ?

**Comment by ashygee** [comment]
I'm good with the new version with the serifed 1

**Comment by colebemis** [comment]
@ashygee What are your thoughts on the shorter bottom line mentioned in [this comment](https://github.com/primer/octicons-v2/issues/208#issuecomment-588062927)? I'm still leaning towards the slightly shorter line.

**Comment by edokoa** [comment]
@ashygee said the shorter one in Figma
