### ISSUE TITLE
Mortar board

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#210]
![image](https://user-images.githubusercontent.com/694831/73438979-36daae80-434f-11ea-9f1d-3744928b4f1d.png)

**Comment by ashygee** [comment]
@colebemis and I spoke today and this looks good but let's remove the dot. once that's done then we can get this added to the viewer and close the issue.

cc @edokoa

**Comment by colebemis** [comment]
https://primer.style/octicons-v2/mortar-board-16
https://primer.style/octicons-v2/mortar-board-24
