### ISSUE TITLE
Horizontal rule

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#212]
![image](https://user-images.githubusercontent.com/694831/73439092-5eca1200-434f-11ea-8c00-ce3f8e6ae790.png)

**Comment by ashygee** [comment]
@edokoa here are some ideas that @colebemis and I explored today

<img width="156" alt="Screenshot 2020-02-13 17 07 44" src="https://user-images.githubusercontent.com/10384315/74492473-d33e9e00-4e83-11ea-80b7-964672f5fda7.png">
<img width="158" alt="Screenshot 2020-02-13 17 08 23" src="https://user-images.githubusercontent.com/10384315/74492476-d46fcb00-4e83-11ea-8b33-353d8cc50a8a.png">

We both like the single line better.

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=597%3A1448

**Comment by colebemis** [comment]
https://primer.style/octicons-v2/horizontal-rule-16

**Comment by edokoa** [comment]
Should we group it with other elements instead of the list and quote? In those icons, the lines make reference to text lines. I think it would work better if we switched it to the side of the code and link buttons.

**Comment by ashygee** [comment]
> Should we group it with other elements instead of the list and quote? In those icons, the lines make reference to text lines. I think it would work better if we switched it to the side of the code and link buttons.

yeah i think so. @colebemis and i mentioned that yesterday and seeing you bring it up to @edokoa makes me feel more confident that it's a stronger recommendation.
