### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#214]
![image](https://user-images.githubusercontent.com/694831/73439210-8faa4700-434f-11ea-9fa7-4ec60bd4e7c6.png)

Related to #205 (Sign Out)

**Comment by colebemis** [comment]
Here's another option for sign-in/sign-out: 

![image](https://user-images.githubusercontent.com/4608155/74774039-e2d53280-5247-11ea-8c75-a5d60ffc9153.png)

**Comment by colebemis** [comment]
More options:

![image](https://user-images.githubusercontent.com/4608155/74774675-0351bc80-5249-11ea-934d-89ae35bb4f95.png)

**Comment by ashygee** [comment]
Notes from today's sync:

We're moving forward with this styling.
![image](https://user-images.githubusercontent.com/10384315/74778135-cf2dca00-524f-11ea-974c-b0b3cbf259df.png)
