### ISSUE TITLE
Read/unread boolean filter icon for mobile notifications

### ISSUE THREAD

**Issue by brianlovin** [primer/octicons-v2#217]
Hey team, we've been iterating for quite a bit on how to re-introduce read/unread filters into the mobile apps. This is the latest iteration we've aligned on:

https://pxlc.at/post/ck60g3l5i8hyh0770sn0zcuif

We need help finding a better icon that has an on/off state which would indicate that the user is filtering by unread-only, versus looking at all notifications. My current mock just uses a stroked/filled check-in-circle icon, but I think the checkmark feels too similar to "done" so it could be confusing.

Would love some ideas and help here!

Ref discussion: https://github.com/github/pe-mobile-android/issues/683

**Comment by ashygee** [comment]
@brianlovin @rnystrom has there been any more discussion on this?

**Comment by rnystrom** [comment]
I think we can close this. We shipped a filter icon on Inbox and moved the read/unread into the Filter tray as an OS toggle/switch.
