### ISSUE TITLE
Repeated metaphor - request-changes/diff/suggest-changes

### ISSUE THREAD

**Issue by ashygee** [primer/octicons-v2#227]
@colebemis @edokoa I just realized that we have the same icon for 16px and 24px named differently. Should this be [`request-changes`(24px)](https://octicons-v2.now.sh/octicons-v2/request-changes-24) or [`diff` (16px)](https://octicons-v2.now.sh/octicons-v2/diff-16)? This is also referenced in #177 where we agreed to use [`file-diff` (16px)](https://octicons-v2.now.sh/octicons-v2/file-diff-16) for suggesting changes.

diff | file-diff | request-changes
:-: | :-: | :-:
![image](https://user-images.githubusercontent.com/10384315/74600190-b8665800-5042-11ea-9251-b41fb9d7e7f3.png) | ![image](https://user-images.githubusercontent.com/10384315/74600179-91a82180-5042-11ea-885a-fb89bc37c8df.png) | ![image](https://user-images.githubusercontent.com/10384315/74600184-a71d4b80-5042-11ea-9d41-5c8a77482eab.png)

**Comment by edokoa** [comment]
I think it should be "diff", because "request-changes" makes reference to the use of the icon, no the icon itself. We maybe have to check how icons are named and how we plan to do it (naming icon meaning vs. use)

**Comment by colebemis** [comment]
I agree. Let's rename the 24px `request-changes` icon to `diff`
