### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by ashygee** [primer/octicons-v2#228]
| Original |
| :-: |
![image](https://user-images.githubusercontent.com/10384315/74762315-74d24080-5232-11ea-9986-78bd1dde0dbf.png)

Usage:
https://styleguide.github.com/
<img width="1164" alt="Screenshot 2020-02-18 09 37 21" src="https://user-images.githubusercontent.com/10384315/74762342-8582b680-5232-11ea-9237-3cd19b3b32fd.png">

**Comment by ashygee** [comment]
According to our google sheet this is only used on the styleguide atm. Even so, I think we should anticipate this icon for future use.

**Comment by edokoa** [comment]
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=1109%3A3275

I had worked on this before and had three early versions. I'm not sure if the "clean version is not too simple, but I was not happy with the line detail in the right one.

![image](https://user-images.githubusercontent.com/694831/83028795-336fdf00-a032-11ea-9e12-0eaa9a1ec4d0.png)


I made a proper 16/24 version of it fixing some problems. I have the feeling the 24px might be 1px too low, but I was keeping it like this so it aliases only in the inside at 1:1.

![image](https://user-images.githubusercontent.com/694831/83028103-433af380-a031-11ea-8903-7668c3fe39d0.png)

**16px**

![image](https://user-images.githubusercontent.com/694831/83028600-f0ae0700-a031-11ea-9877-f82b6896184d.png)
![image](https://user-images.githubusercontent.com/694831/83028572-e986f900-a031-11ea-8220-1aa5eb43b6ef.png)

**24px**

![image](https://user-images.githubusercontent.com/694831/83027735-c3148e00-a030-11ea-8c57-359df7ce7606.png)
![image](https://user-images.githubusercontent.com/694831/83027922-0a028380-a031-11ea-8ac5-5b99f64c4c19.png)

**Comment by ashygee** [comment]
I think the top feels too tall. In a gem usually the top is a little more squished. 
![image](https://user-images.githubusercontent.com/10384315/83202867-67fc9d00-a0fd-11ea-858e-2655eb2b4c27.png)

**Comment by edokoa** [comment]
I'll work on this version. you're right with the top part.

**Comment by edokoa** [comment]
I pushed the middle line a little bit to avoid aliasing. Maybe we could keep all the lines at 24px but only the outline at 16px?

It feels more dense than other icons at 16

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=1119%3A3956

![image](https://user-images.githubusercontent.com/694831/83276323-b6c73700-a1d0-11ea-92f3-f2619b947d6e.png)
![image](https://user-images.githubusercontent.com/694831/83276333-ba5abe00-a1d0-11ea-81c2-0d56740c5239.png)

**Comment by colebemis** [comment]
Here are a few more options for the 24px ruby icon:

![image](https://user-images.githubusercontent.com/4608155/83463495-0604a600-a423-11ea-8063-03c951d8fe9e.png)

I think the left one is my favorite.

**Comment by edokoa** [comment]
Yes, I was trying with the added lines but I think it works better without. 👍
