### ISSUE TITLE
24px - cheklist

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#234]
#114 

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=723%3A1495

![image](https://user-images.githubusercontent.com/694831/74932906-2f08aa00-53e3-11ea-9761-2bd6cf8dbac7.png)

**Comment by edokoa** [comment]
In this one I was trying two sizes. I thought the big one looked too sparse (I used the checkmark size from the circular checkmark icons)

**Comment by ashygee** [comment]
@edokoa I agree with you. I prefer the bottom version better too.
