### ISSUE TITLE
24px - org

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#237]
#222 

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=723%3A1570

![image](https://user-images.githubusercontent.com/694831/74933526-780d2e00-53e4-11ea-9e23-0327dde808b2.png)

**Comment by edokoa** [comment]
In this one I thought using a 3 column layout for the windows would look better (it feels too empty with 2). It generates some aliasing in the middle column at 24px, but it's not very noticeable.

**Comment by ashygee** [comment]
@edokoa i removed a row of windows and spaced them out a bit more so it feels less cramped

![image](https://user-images.githubusercontent.com/10384315/75216793-0d445580-574a-11ea-8a7b-6dbff3d29938.png)
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=752%3A1994
