### ISSUE TITLE
24px - repo / repo-force-push

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#249]
#28 #51 

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=723%3A1924

![image](https://user-images.githubusercontent.com/694831/74946417-8c0f5a80-53f9-11ea-96ce-2d2c843285eb.png)

**Comment by ashygee** [comment]
close from conversation in #192
