### ISSUE TITLE
24px - diff icons

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#250]
#152 

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=723%3A1925

![image](https://user-images.githubusercontent.com/694831/74938480-6466c500-53ee-11ea-962d-4b8a3db7e198.png)

**Comment by edokoa** [comment]
@ashygee made the version with the big arrowhead. We have to discuss how arrows work in the set.


![image](https://user-images.githubusercontent.com/694831/74946220-4357a180-53f9-11ea-8200-c06dc359387e.png)

**Comment by ashygee** [comment]
👍 for the set plus the updated arrowhead.
