### ISSUE TITLE
24px -  device

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#255]
#155 

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=723%3A1950

![image](https://user-images.githubusercontent.com/694831/74943906-726c1400-53f5-11ea-8f3f-0c72a2f7619d.png)

**Comment by ashygee** [comment]
Do we want to add a little detail to the larger icons @colebemis?
