### ISSUE TITLE
24px - file-directory / file-directory-fill

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#264]
#67 

There's a ghost pixel we should fix in the 24px folder icons:

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=736%3A1393

![image](https://user-images.githubusercontent.com/694831/75031654-03e78e80-54a7-11ea-849e-516b0264de86.png)

**Comment by ashygee** [comment]
@edokoa I'm not seeing a ghost pixel in these images. is it fixed?

**Comment by edokoa** [comment]
I fixed it. It was in the top long borded before.
