### ISSUE TITLE
24px - desktop download

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#271]
#189 

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=738%3A1555

![image](https://user-images.githubusercontent.com/694831/75043731-ce4f9f00-54c0-11ea-9e6b-8ad2eef1c87d.png)

**Comment by edokoa** [comment]
Both arrow versions

**Comment by ashygee** [comment]
right version with line arrow 👍
