### ISSUE TITLE
24px - link external

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#272]
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=738%3A1592

![image](https://user-images.githubusercontent.com/694831/75044559-23d87b80-54c2-11ea-8d23-e70f819137a5.png)

**Comment by edokoa** [comment]
Slightly smaller version on the right to have inner aliasing

**Comment by ashygee** [comment]
@edokoa I think we can go with the line arrow here:

![image](https://user-images.githubusercontent.com/10384315/75216409-c43fd180-5748-11ea-9380-6beb189ed524.png)

cc @colebemis
