### ISSUE TITLE
24px - Eye / Eye-slash

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#273]
We have a 24px eye but it doesn't match the 16 px version.

![image](https://user-images.githubusercontent.com/694831/75148982-368cc380-5701-11ea-92a4-e2d66eab2827.png)
![image](https://user-images.githubusercontent.com/694831/75149010-499f9380-5701-11ea-8ce3-262e1fe9f045.png)

**Comment by edokoa** [comment]
From left to right:

- original 24px icon with fill / without border
- original 24px icon with fill + border
- Adapted pupil (small)
- Adapted pupil (medium)

I'd say the 3rd one is the one which looks more consistent with the 16px version, but if the pupil is too small we can go for the 4th version.

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=746%3A1582

![image](https://user-images.githubusercontent.com/694831/75149209-c03c9100-5701-11ea-9d07-8b481c706d22.png)

**Comment by edokoa** [comment]
The slash version will depend on which eye we pick

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=746%3A2045

![image](https://user-images.githubusercontent.com/694831/75155269-f254ef80-570f-11ea-816d-d5a2ee32d107.png)

**Comment by ashygee** [comment]
I prefer `Adapted pupil small`. It feels the most balanced and least intimidating 😂 

@colebemis what do you think?
