### ISSUE TITLE
24px - diff file

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#275]
I think the 2nd one feels more balanced

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=746%3A1718

![image](https://user-images.githubusercontent.com/694831/75152380-2e388680-5709-11ea-9d77-5ad24719c6cd.png)

**Comment by ashygee** [comment]
I agree. I prefer the spacing on the second (right side) version.
