### ISSUE TITLE
24px - terminal

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#280]
#162 

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=746%3A2274

![image](https://user-images.githubusercontent.com/694831/75158529-9772c680-5716-11ea-9d8f-53236c3ed9ef.png)

**Comment by ashygee** [comment]
I think I prefer the left version. @colebemis what do you think?
