### ISSUE TITLE
24px - Copy

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#287]
#119 

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=746%3A2588

![image](https://user-images.githubusercontent.com/694831/75165709-13730b80-5723-11ea-9a0b-d4123103b473.png)

**Comment by ashygee** [comment]
@edokoa I prefer the third version from the left. 

@colebemis this metaphor ties into a question @edokoa had earlier:

> Clippy icon: It's similar to 'copy' in meaning, right now it's in the viewer, but not in the 32px source. Should we add this icon to the set even if it's substituted by 'copy'?

Is this version of the copy icon the direction we want to go for the "copy" metaphor or should we continue to include `clippy` too?

**Comment by colebemis** [comment]
Earlier we chose to abandon this metaphor in favor of the clipboard metaphor. I must have for got to remove this remove the viewer. Sorry for the confusion @edokoa.
