### ISSUE TITLE
Formally add internal-repo icon

### ISSUE THREAD

**Issue by jasonlong** [primer/octicons-v2#300]
@iolsen pointed out to me that we never added the `internal-repo` icon to Octicons. @pmarsceill is the original designer and I added it to github.com when we added the option for repos to be internal (vs. public or private).

We're still using the raw svg in our codebase:

```svg
<svg width="26" height="32" viewBox="0 0 13 16"><path d="M10 2a1 1 0 0 0 1 1h1v13h1V3a1 1 0 0 0-1-1h-2zM7 3v1H6V3a1 1 0 0 1 1-1h2a1 1 0 0 1-1 1H7z"></path><path d="M10 4h1v2h-1V4zM10 7h1v2h-1V7zM10 10h1v2h-1v-2zM10 13h1v2h-1v-2zM9 0h1v1H9V0zM8 2a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1H8zM3 11h1v-1H3v1zM3 6h1v1H3V6zM3 8h1v1H3V8z"></path><path fill-rule="evenodd" clip-rule="evenodd" d="M0 12v2c0 .55.45 1 1 1h1v1l1-.5 1 .5v-1h4c.55 0 1-.45 1-1v-2H0zm1 1h7v1H4v-1H2v1H1v-1zM0 5c0-.55.45-1 1-1h7c.55 0 1 .45 1 1v7H8V5H2v7H0V5z"></path></svg>
```

Example from the github PR (not posting link here since this repo is public):

![image](https://user-images.githubusercontent.com/6104/67905553-1d577a00-fb48-11e9-9d23-71cbd72afabf.png)

**Comment by ashygee** [comment]
@colebemis @edokoa we will need to add this to Octicons v2 as well. i will take care of adding the current icon to v1 for now.

@jasonlong do we have the Figma file for this or just the source svg?

**Comment by jasonlong** [comment]
@ashygee If there's a figma file for it, @pmarsceill would have it. It may even be from the Sketch days of yesteryear.

**Comment by pmarsceill** [comment]
@ashygee I found it. DMing to you.

**Comment by edokoa** [comment]
I made a few quick explorations. Would we need a 16px version of this or only the 24px?

![image](https://user-images.githubusercontent.com/694831/75975347-a147b700-5ed8-11ea-923c-a0bf81d7ee99.png)

**Comment by ashygee** [comment]
@edokoa I like the first and the third columns (from the left). Also, it appears that 24px might be the only size used atm but I do think we should consider what solution we might provide for a 16px icon too. 

@jasonlong is the internal-repo icon used in a smaller context anywhere else?

**Comment by edokoa** [comment]
I just wanted to add another version I thought about after posting this, the inverted variation of the 4th

![image](https://user-images.githubusercontent.com/694831/76005739-bc7fea00-5f0b-11ea-9f86-a896b814f625.png)

**Comment by colebemis** [comment]
@jasonlong Does `internal-repo` mean "internal to an enterprise" in general or "internal to github" specifically?

**Comment by iolsen** [comment]
It means "internal to an enterprise" in general.

**Comment by ashygee** [comment]
@edokoa I like these but feel it might be hard to discern the avatar for our enterprise customers in within this space.  I think I still prefer this version better since it gives an indication that the repo exists within the enterprise account and ties together with our icon for "enterprise"

![image](https://user-images.githubusercontent.com/10384315/76118027-e4219180-5fa1-11ea-8380-7cfe2d0789ca.png)

That being said, I do think we could connect it more so that it doesn't feel as if the avatar is a bat signal 😂 

![](https://media0.giphy.com/media/15BuYJbJlNvBC/giphy.gif?cid=790b7611c6b0e7374a8d175c21ac34fc28f5f0cfa61a6c14&rid=giphy.gif)

**Comment by ashygee** [comment]
> 👋🏽friendly bump from `iam` as we currently are [hardcoding the SVG](https://github.com/github/github/blob/2662e135638b6735d8101098de416b57564f1dc7/app/views/edit_repositories/pages/managed_access.html.erb#L22-L27) in `:repo/settings/access` which happens to render badly in Safari [github/github#133353](https://github.com/github/github/issues/133353)

@CamiloGarciaLaRotta @jasonlong https://github.com/primer/octicons/blob/master/CHANGELOG.md#950

**Comment by jasonlong** [comment]
It’s not entirely clear from the screenshot in the original message up top, but the GitHub logo is actually not part of the icon. We show the org avatar of whatever the user’s org is in that negative space.

**Comment by edokoa** [comment]
I was doing some tests with other org icons. We could use the small repo icon combined with a 30x30 org icon (half the normal size).

![image](https://user-images.githubusercontent.com/694831/76232169-9c5f6c00-6226-11ea-8544-fb4eea08f0f9.png)

**Comment by edokoa** [comment]
Source is in https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=876%3A297

**Comment by ashygee** [comment]
@colebemis should we add using the 16px `repo` icon for the current `internal-repo` icon to the list of re-mapping? I'm not sure if @jasonlong and @CamiloGarciaLaRotta might have additional work on their end to reposition and resize the org avatar for this.

**Comment by CamiloGarciaLaRotta** [comment]
👋🏽@ashygee I would unfortunately not be able to tell if the 16x version of `internal-repo` works for us.

We currently use the hardcoded internal SVG in  [`managed_access.html.erb`](https://github.com/github/github/blob/master/app/views/edit_repositories/pages/managed_access.html.erb#L27). https://github.com/github/github/pull/138339 has the change required to use the octicon, but running locally yields a runtime error, I believe the octicon is not yet available in the bundled version of the monolith. Should I wait for the team to officially bump the octicon version in the monolith?

**Comment by jasonlong** [comment]
Yeah we'll need to coordinate the rollout of the new icon since the avatar has custom absolutely positioned coordinates.
