### ISSUE TITLE
[Icon request] Complete Arrow direction sets for both sizes

### ISSUE THREAD

**Issue by brianlovin** [primer/octicons-v2#303]
It would be fantastic to see parity between arrow sets, in both sizes, for all directions. For example, at the 16p size we're missing `arrow-up-left` and for both sets we're missing `arrow-up-right`

<img width="910" alt="Screenshot 2020-03-11 14 00 14" src="https://user-images.githubusercontent.com/1923260/76463557-d18fc980-63a0-11ea-95dc-8cde32f56c03.png">

**Comment by edokoa** [comment]
@colebemis we should have the 16px `arrow-up-left `? As for the other direction, was the idea to flip this one somehow or should we make all the directions?

**Comment by colebemis** [comment]
@edokoa We should make all directions 👍

**Comment by ashygee** [comment]
Yeah i definitely agree @brianlovin. Originally we were focusing on what was just currently needed but we should definitely expand the set to be complete. 

Here is what @edokoa created today. I'll update the viewer and our source files to include them.
