### ISSUE TITLE
briefcase

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#310]
![image](https://user-images.githubusercontent.com/694831/83005803-8f763b80-a011-11ea-9fe4-e5146012a60e.png)

**Comment by edokoa** [comment]
Some work on this icon was already made in this issue https://github.com/primer/octicons-v2/issues/161

**Comment by edokoa** [comment]
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=1109%3A3125

![image](https://user-images.githubusercontent.com/694831/83018360-74adc200-a025-11ea-92e0-b1a25d5a8ad6.png)


**16px**

![image](https://user-images.githubusercontent.com/694831/83017875-b2f6b180-a024-11ea-8b5f-fca35b4b9461.png)
![image](https://user-images.githubusercontent.com/694831/83017977-d6b9f780-a024-11ea-8ba8-7473e255740c.png)


**24px**

![image](https://user-images.githubusercontent.com/694831/83017519-1b915e80-a024-11ea-9468-2597cf969ba3.png)
![image](https://user-images.githubusercontent.com/694831/83017683-5c897300-a024-11ea-926e-025d6270446c.png)

**Comment by ashygee** [comment]
I was getting slight toolbox vibes and was playing around with these variations. 

![image](https://user-images.githubusercontent.com/10384315/83203712-f1609f00-a0fe-11ea-9ce3-fa8ece6de7b1.png)

@edokoa what do you think about a little more curve?

cc @colebemis

**Comment by colebemis** [comment]
Ooo I like the first one @ashygee ❤️

**Comment by edokoa** [comment]
I like them. I like the first and second most, but maybe the second gets lost in small sizes.

**Comment by edokoa** [comment]
What about this 24px version?

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=1119%3A2122

![image](https://user-images.githubusercontent.com/694831/83258223-2f6cca00-a1b6-11ea-9f1f-220c3bea7722.png)





![image](https://user-images.githubusercontent.com/694831/83258294-4c090200-a1b6-11ea-939f-2b2d45004f91.png)

**Comment by colebemis** [comment]
Looks good to me 👍

**Comment by colebemis** [comment]
I opened a PR to add this to Octicons: https://github.com/primer/octicons/pull/434

I'll merge when I have approvals from @ashygee and @edokoa
