### ISSUE TITLE
repo-clone

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#312]
![image](https://user-images.githubusercontent.com/694831/83006486-95b8e780-a012-11ea-9f71-d01421cdef4e.png)

**Comment by edokoa** [comment]
I think the current concept is too complex to display at 16px, should we change it for something like this?
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=1109%3A3990

![image](https://user-images.githubusercontent.com/694831/83047732-11ce2200-a049-11ea-855a-8801f2a445ad.png)

**Comment by ashygee** [comment]
This feels more like adding a repo rather than cloning it. I wonder if we can move away from the book and think of metaphors just on "clone"

**Comment by edokoa** [comment]
What about rescuing this one:

| 16px | 24px |
| :---: | :---: |
| <img width="16" alt="copy (1)" src="https://user-images.githubusercontent.com/4608155/69267680-84ce7b80-0b82-11ea-909d-f3d8a962da9e.png"> | <img width="24" alt="copy" src="https://user-images.githubusercontent.com/4608155/69267632-69fc0700-0b82-11ea-87ea-4246f80f3fa0.png"> |


from here?

https://github.com/primer/octicons-v2/issues/119

**Comment by colebemis** [comment]
@edokoa I was thinking the same thing 👍  We probably want to rename it `clone` or `duplicate` instead of `repo-clone` if we go this direction.

**Comment by colebemis** [comment]
I found it in stafftools 😅 

![image](https://user-images.githubusercontent.com/4608155/83689516-ff516c80-a5a3-11ea-8c89-29862663f150.png)

**Comment by colebemis** [comment]
👆 I feel like we could replace this usage with either the `repo` or `repo-forked` icon. I don't think we need to design a special `repo-clone` icon. At the very least, it shouldn't block us from merging the `v2` branch.

**Comment by colebemis** [comment]
I have a PR open to remove all usages of the `repo-clone` icon: https://github.com/github/github/pull/145691
