### ISSUE TITLE
paintcan

### ISSUE THREAD

**Issue by edokoa** [primer/octicons-v2#313]
![image](https://user-images.githubusercontent.com/694831/83007824-8044bd00-a014-11ea-9714-2c984265bc7c.png)

**Comment by edokoa** [comment]
Where does this appear in the UI?

**Comment by edokoa** [comment]
We have to check if this icon is more about the bucket or about the pain, or what kind of metaphor it represents. Is it "fill" ?

**Comment by colebemis** [comment]
Try a paint brush instead

**Comment by edokoa** [comment]
What about this?
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=1200%3A463

![image](https://user-images.githubusercontent.com/694831/83880758-f1385300-a73f-11ea-8e57-2ac3866a3308.png)

![image](https://user-images.githubusercontent.com/694831/83880397-58093c80-a73f-11ea-82b1-e0e71c540ee4.png)

Another option would be to make it vertical (like the wrench) but I think that would cut the object and make it more difficult to understand.
